server:
  port: 8090
#RABBITMQ
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: 'false' #desabilita a tentativa de consumir a mensagem, evitando um looping no reprocessamento
        retry:
          enabled: 'true' #habilita o retry
          max-attemps: '3' #numero de tentativas = 3
          initial-interval: 5s #em um intervalo de 5 segundos
          multiplier: '2' #multiplicando o intervalo de 5 segundos por 2
